--the game doesn't save unless product and publisher are added for some reason, so I added them
product = "Angry SDK"
publisher = "Assasain_2.0"
name = "Angry SDK"
width = 100
height = 200
orientation = 0
datapath = "data"
imagePath = "images"
fontPath = "fonts"
audioPath = "audio"
localizationPath = "localization"
levelPath = "/levels"
scriptPath = "scripts"
commonScriptPath = "scripts_common"
shaderPath = "shaders"
deviceModel = "windows"
fullscreen = false
showCursor = true
singleton = true
renderer = { "gl2", "gl1" }
